### PR TITLE
added touch events

### PR DESCRIPTION
**Pull request by clearlysid**
Used touch events to make this work on mobile. No external library, just plain vanilla js. Also, my first contribution to an open source project!

### CODE REVIEW

**Comment by lmgonzalves** [comment]
Thanks and Welcome!
Please avoid repeating code. In this case, you can extract the code that handle the events to external functions.
Make the changes and I will be happy to merge.

**Comment by clearlysid** [comment]
Understood sir, I'm on it!

**Comment by clearlysid** [comment]
Here, I think this does it yes? I offloaded the code to a function and called it with different parameters depending on whether it is clicked or touched.

**Comment by lmgonzalves** [comment]
Thanks!

**Pull request merged**
